version: '3.3'

services:
  web:
    build: ./hello_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hello_django/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dockuser
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=docker

volumes:
  postgres_data: